import { Flex } from '@theme-ui/components';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Article } from '../../types/types';
import { useArticles } from '../api/hooks';
import ArticlePreview from '../article/ArticlePreview';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { data, loading, error } = useArticles();

  if (loading) return <div>Loading...</div>;
  if (error) return <div>{error}</div>;

  const { result } = data;

  return (
    <div className={styles.container}>
      <Head>
        <title>wiki-re-reborn</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>wiki-re-reborn</a>
        </h1>
        <Flex>
          {result.map((article: Article, key: number) => (
            <ArticlePreview data={article} key={key} />
          ))}
        </Flex>
      </main>
    </div>
  );
};

export default Home;
